dm:
    [10., 20., 30., 40.]

period:
    [0.001, 0.0005, 1., 2., 3., 4.]

maxFlux:
    5

minFlux:
    0.1

detectScore:
    0.7

taskid:
    16

databasePath:
    /public/home/mcc/work/test-simPipe/Parallel-test/simPipe1Parallel1/simPipe.db
